server:
  port: 8888

spring:
  profiles:
    active: jdbc
  application:
      name: config-server
  cloud:
    config:
      label: master
      server:
        jdbc:
          sql: SELECT `KEY`, `VALUE` from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
          order: 0
        default-label: master
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 50

